In [1]:
!pip install geopandas folium scipy pandas numpy

Requirement already satisfied: geopandas in /usr/local/lib/python3.12/dist-packages (1.1.2)
Requirement already satisfied: folium in /usr/local/lib/python3.12/dist-packages (0.20.0)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (1.16.3)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: pyogrio>=0.7.2 in /usr/local/lib/python3.12/dist-packages (from geopandas) (0.12.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from geopandas) (26.0)
Requirement already satisfied: pyproj>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from geopandas) (3.7.2)
Requirement already satisfied: shapely>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from geopandas) (2.1.2)
Requirement already satisfied: branca>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from folium) (0.8.2)
Requirement already satisfied: jinja2>=2.9 in /usr/local/lib/python3.12/dist-packages (from folium) (3.1.6)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from folium) (2.32.4)
Requirement already satisfied: xyzservices in /usr/local/lib/python3.12/dist-packages (from folium) (2025.11.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2>=2.9->folium) (3.0.3)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from pyogrio>=0.7.2->geopandas) (2026.2.25)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->folium) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->folium) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->folium) (2.5.0)

In [2]:
import pandas as pd

url = "https://raw.githubusercontent.com/durlabhjilegend-lgtm/delhi-aqi-dataset/main/aqi_data.csv"

df = pd.read_csv(url)

df["timestamp"] = pd.to_datetime(df["timestamp"])

df.head()

,station,latitude,longitude,aqi,timestamp
0,"DITE Okhla, Delhi, Delhi, India",28.531314,77.270686,209,2026-03-07 16:07:26.633441
1,"Sector - 125, Noida, India",28.544761,77.323126,349,2026-03-07 16:07:26.633445
2,"Anand Vihar, Delhi, Delhi, India",28.650800,77.315200,175,2026-03-07 16:07:26.633446
3,"Lodhi Road, Delhi, Delhi, India",28.589701,77.221917,129,2026-03-07 16:07:26.633446
4,"Bramprakash Ayurvedic Hospital, Najafgarh, Del...",28.572714,76.933433,109,2026-03-07 16:07:26.633447

In [4]:
latest = df.sort_values("timestamp").groupby("station").tail(1)
print(latest)

                                                station   latitude  longitude  \
7238           Knowledge Park - V, Greater Noida, India  28.557054  77.453663
7239                         Teri Gram, Gurugram, India  28.427500  77.146500
7241                             Loni, Ghaziabad, India  28.757294  77.278792
7240            Sri Auribindo Marg, Delhi, Delhi, India  28.528344  77.189304
7242           Pooth Khurd, Bawana, Delhi, Delhi, India  28.775796  77.046251
7243                           Sector-116, Noida, India  28.569230  77.393848
7244              ITI Jahangirpuri, Delhi, Delhi, India  28.733016  77.171970
7245               Burari Crossing, Delhi, Delhi, India  28.725646  77.203384
7246                   Anand Vihar, Delhi, Delhi, India  28.650800  77.315200
7247                          Pusa, Delhi, Delhi, India  28.636997  77.172248
7248                  Punjabi Bagh, Delhi, Delhi, India  28.668300  77.116700
7249                        Narela, Delhi, Delhi, India  28.820629  77.101099
7250                      Indirapuram, Ghaziabad, India  28.646233  77.358075
7251             Satyawati College, Delhi, Delhi, India  28.695720  77.181295
7252  ITI Shahdra, Jhilmil Industrial Area, Delhi, D...  28.672114  77.313832
7253                        Alipur, Delhi, Delhi, India  28.815691  77.152491
7254                     Arya Nagar, Bahadurgarh, India  28.670100  76.925400
7255         Knowledge Park - III, Greater Noida, India  28.472720  77.482000
7256                       Vasundhara, Ghaziabad, India  28.660335  77.357256
7257                     Sanjay Nagar, Ghaziabad, India  28.685382  77.453839
7258                         Sector-51, Gurugram, India  28.422700  77.066700
7259  Dr. Karni Singh Shooting Range, Delhi, Delhi, ...  28.499727  77.267095
7260                         Sector - 125, Noida, India  28.544761  77.323126
7261   PGDAV College, Sriniwaspuri, Delhi, Delhi, India  28.566827  77.251418
7262                           ITO, Delhi, Delhi, India  28.628577  77.241036
7263                        Mundka, Delhi, Delhi, India  28.682410  77.030469
7264  Bramprakash Ayurvedic Hospital, Najafgarh, Del...  28.572714  76.933433
7265                  NISE Gwal Pahari, Gurugram, India  28.422681  77.148944
7266                        Sector 30, Faridabad, India  28.441700  77.321700
7267                    DITE Okhla, Delhi, Delhi, India  28.531314  77.270686
7269                    R.K. Puram, Delhi, Delhi, India  28.564800  77.174400
7268  Mother Dairy Plant, Parparganj, Delhi, Delhi, ...  28.620171  77.287705
7270                    Lodhi Road, Delhi, Delhi, India  28.589701  77.221917
7271                      Shadipur, Delhi, Delhi, India  28.651553  77.158042
7272  Shaheed Sukhdev College of Business Studies, R...  28.732743  77.118788
7273                          Sector - 62, Noida, India  28.624548  77.357710
7274                Vikas Sadan Gurgaon, Gurgaon, India  28.450124  77.026305
7275             CRRI Mathura Road, Delhi, Delhi, India  28.551729  77.275037
7276      Jawaharlal Nehru Stadium, Delhi, Delhi, India  28.582846  77.234366
7277                   Mandir Marg, Delhi, Delhi, India  28.634100  77.200500
7278  Major Dhyan Chand National Stadium, Delhi, Del...  28.612498  77.237388
7279                     Aya Nagar, Delhi, Delhi, India  28.482888  77.126748
7280  Delhi Institute of Tool Engineering, Wazirpur,...  28.700505  77.165603
7281                             Sector-1, Noida, India  28.589800  77.310100
7283  Sonia Vihar Water Treatment Plant DJB, Delhi, ...  28.710066  77.246220
7282  National Institute of Malaria Research, Sector...  28.576909  77.075898
7284                           DTU, Delhi, Delhi, India  28.749722  77.116281

      aqi                  timestamp
7238  144 2026-03-12 11:49:07.779773
7239  168 2026-03-12 11:49:07.779777
7241  178 2026-03-12 11:49:07.779778
7240   97 2026-03-12 11:49:07.779778
7242  123 2026-03-12 11:49:07.779779
7243   87 2026-03-12 11:49:07.779780
7244  103 2026-03-12 11:49:07.779780
7245  107 2026-03-12 11:49:07.779781
7246   98 2026-03-12 11:49:07.779781
7247  115 2026-03-12 11:49:07.779782
7248  132 2026-03-12 11:49:07.779785
7249  102 2026-03-12 11:49:07.779785
7250  113 2026-03-12 11:49:07.779786
7251  111 2026-03-12 11:49:07.779786
7252  113 2026-03-12 11:49:07.779787
7253  114 2026-03-12 11:49:07.779787
7254  142 2026-03-12 11:49:07.779788
7255   82 2026-03-12 11:49:07.779789
7256  192 2026-03-12 11:49:07.779789
7257  123 2026-03-12 11:49:07.779790
7258  182 2026-03-12 11:49:07.779790
7259   91 2026-03-12 11:49:07.779791
7260   91 2026-03-12 11:49:07.779791
7261  109 2026-03-12 11:49:07.779792
7262  161 2026-03-12 11:49:07.779793
7263  131 2026-03-12 11:49:07.779793
7264   87 2026-03-12 11:49:07.779794
7265  100 2026-03-12 11:49:07.779794
7266    - 2026-03-12 11:49:07.779795
7267  118 2026-03-12 11:49:07.779795
7269  107 2026-03-12 11:49:07.779796
7268  103 2026-03-12 11:49:07.779796
7270  155 2026-03-12 11:49:07.779797
7271  161 2026-03-12 11:49:07.779800
7272  113 2026-03-12 11:49:07.779800
7273  105 2026-03-12 11:49:07.779801
7274  188 2026-03-12 11:49:07.779801
7275  139 2026-03-12 11:49:07.779802
7276  110 2026-03-12 11:49:07.779802
7277  164 2026-03-12 11:49:07.779803
7278  131 2026-03-12 11:49:07.779803
7279   80 2026-03-12 11:49:07.779804
7280  145 2026-03-12 11:49:07.779805
7281   92 2026-03-12 11:49:07.779805
7283   97 2026-03-12 11:49:07.779806
7282  109 2026-03-12 11:49:07.779806
7284   95 2026-03-12 11:49:07.779807

In [5]:
import geopandas as gpd

stations = gpd.GeoDataFrame(
    latest,
    geometry=gpd.points_from_xy(latest.longitude, latest.latitude),
    crs="EPSG:4326"
)

In [6]:
import folium

m = folium.Map(location=[28.61,77.23], zoom_start=11, tiles="cartodbpositron")

for _,row in stations.iterrows():

    folium.CircleMarker(
        location=[row["latitude"],row["longitude"]],
        radius=6,
        color="blue",
        fill=True,
        popup=f"{row['station']} | AQI {row['aqi']}"
    ).add_to(m)

m

In [8]:
stations.columns

Index(['station', 'latitude', 'longitude', 'aqi', 'timestamp', 'geometry'], dtype='object')

In [9]:
stations["aqi"] = pd.to_numeric(stations["aqi"], errors="coerce")

In [10]:
stations = stations.dropna(subset=["aqi"])

In [11]:
import numpy as np
from scipy.spatial import cKDTree

coords = stations[["longitude","latitude"]].to_numpy()

values = stations["aqi"].to_numpy()

tree = cKDTree(coords)

In [12]:
df = df[df["aqi"] != "-"]

In [13]:
import numpy as np
from scipy.spatial import cKDTree

coords = stations[["longitude","latitude"]].to_numpy()
values = stations["aqi"].astype(float).to_numpy()

tree = cKDTree(coords)

def idw(lon,lat,k=6):

    dist,idx = tree.query([lon,lat],k=k)

    weights = 1/(dist**2 + 1e-9)

    return np.sum(weights*values[idx])/np.sum(weights)

In [14]:
from shapely.geometry import Point

xmin,ymin,xmax,ymax = stations.total_bounds

grid_points = []

for x in np.arange(xmin,xmax,0.01):
    for y in np.arange(ymin,ymax,0.01):

        grid_points.append(Point(x,y))

grid = gpd.GeoDataFrame(geometry=grid_points, crs="EPSG:4326")

In [15]:
grid["aqi"] = grid.geometry.apply(lambda p: idw(p.x,p.y))

In [16]:
from folium.plugins import HeatMap

heat_data = [[p.y,p.x,aqi] for p,aqi in zip(grid.geometry,grid["aqi"])]

HeatMap(heat_data,radius=20,blur=15).add_to(m)

m

In [17]:
wards = gpd.read_file(
"https://raw.githubusercontent.com/durlabhjilegend-lgtm/delhi-aqi-dataset/main/delhi_wards.geojson"
)

In [18]:
grid = gpd.sjoin(grid,wards[["WardName","geometry"]],predicate="within")

ward_aqi = grid.groupby("WardName")["aqi"].mean().reset_index()

wards = wards.merge(ward_aqi,on="WardName")

In [19]:
def citizen_alert(aqi):

    if aqi > 300:
        return "Severe pollution: avoid outdoor activity and wear masks."

    elif aqi > 200:
        return "Very poor air: limit outdoor exposure."

    elif aqi > 150:
        return "Poor air quality: sensitive groups should take precautions."

    else:
        return "Air quality acceptable."

In [20]:
def govt_action(aqi):

    if aqi > 300:
        return "Deploy emergency mitigation teams and identify pollution sources."

    elif aqi > 200:
        return "Investigate pollution sources and enforce dust control."

    elif aqi > 150:
        return "Increase monitoring and enforce construction regulations."

    else:
        return "No immediate action required."

In [21]:
wards["citizen_alert"] = wards["aqi"].apply(citizen_alert)

wards["govt_action"] = wards["aqi"].apply(govt_action)

In [22]:
priority = wards.sort_values("aqi",ascending=False)[
    ["WardName","aqi","govt_action"]
]

priority.head(10)

,WardName,aqi,govt_action
36,PAHAR GANJ,157.023022,Increase monitoring and enforce construction r...
228,DELHI GATE,153.721279,Increase monitoring and enforce construction r...
227,CHANDANI MAHAL,151.932199,Increase monitoring and enforce construction r...
152,RAM NAGAR,149.750079,No immediate action required.
11,NARAINA,149.405502,No immediate action required.
39,WEST PATEL NAGAR,147.772429,No immediate action required.
226,JAMA MASJID,146.864928,No immediate action required.
41,KARAM PURA,145.598090,No immediate action required.
150,BALLIMARAN,144.864498,No immediate action required.
42,MOTI NAGAR,144.112414,No immediate action required.